### ISSUE TITLE
OpenSRP Web Location Assignments not updating as they should

### ISSUE THREAD

**Issue by AngelaKabari** [OpenSRP/opensrp-client-anc#964] opened 2023-07-26 10:37 UTC
### Affected App or Server Version

Latest apk (indonesia-reference-app-v1.6.38.apk) + OpenSRP Web v2.3.5

### What kind of support do you need?

This issue was discovered in the course of investigating the cause of Issue #963. 

When I have previously unassigned a team from a location and then I try to re-assign that location to the same team, then we run into the below 400 error. For example I tried to remove the Puskesmas Bunga location from Team Desa Mawar: 
<img width="1551" alt="Team Assignment Error" src="https://github.com/opensrp/opensrp-client-anc/assets/8417097/6a043ffb-90fb-4acc-beff-d06dd85b6c57">

The current state of the `organization_location` table for the 3 locations is as follows:
  location_name  |  organization_name   |        duration         | organization_id | location_id | plan_id 
-----------------+----------------------+-------------------------+-----------------+-------------+--
 Puskesmas Bunga | Team puskesmas Bunga | [2023-07-17,2023-07-21) |             175 |         199 |       2
 Puskesmas Bunga | Team puskesmas Bunga | [2023-07-21,2033-07-22) |             175 |         199 |       2
 Desa Melati     | Team puskesmas Bunga | [2023-07-17,2023-07-22) |             175 |         200 |       2
 Desa Mawar      | Team puskesmas Bunga | [2023-07-17,2023-07-22) |             175 |         201 |       2
 Puskesmas Bunga | Team desa Melati     | [2023-07-17,2023-07-21) |             176 |         199 |       2
 Desa Melati     | Team desa Melati     | [2023-07-17,2033-07-22) |             176 |         200 |       2
 Puskesmas Bunga | Team desa Mawar      | [2023-07-17,2023-07-21) |             177 |         199 |       2
 Puskesmas Bunga | Team desa Mawar      | [2023-07-21,2033-07-22) |             177 |         199 |       2
 Desa Mawar      | Team desa Mawar      | [2023-07-17,2033-07-22) |             177 |         201 |       2
(9 rows)

@hilpitome discovered that the constraint that throws the 400 error occurs when you have `duration`, `organization_id`, `location_id`, and `plan_id` already existing in the `organization_location` table. His hypothesis is that if you assign a team to a location on two different days they will appear twice because the duration is different.

My understanding of the above is that when one changes the assignment of a team to a location, then the previous assignment is not actually updated and so still remains in place. Therefore when you try to change the assignment back to the original location then the 400 error is experienced because the system already has that assignment as a current assignment and therefore cannot re-assign the team to a location that it considers it is already assigned to.

The inability to change assignments of the same team multiple times is preventing us from being able to test the fix for Issue #963. 

### What is the acceptance criteria for your support request?

We should be able to change the location assigned to a team multiple times and have it update accordingly on the server side. For example, I should be able to assign Team desa Mawar to location Puskesmas Bunga, undo that assignment and then re-assign Team desa Mawar to location Puskesmas Bunga once again without experiencing the 400 error.

### Relevant Information

Nothing further.

**Comment by peterMuriuki** [comment] 2023-08-07 14:11
> @hilpitome discovered that the constraint that throws the 400 error occurs when you have `duration`, `organization_id`, `location_id`, and `plan_id` already existing in the `organization_location` table. His hypothesis is that if you assign a team to a location on two different days they will appear twice because the duration is different.

We've encountered this issue before with reveal, so this sounds about right. I however, would like to point out that the issue lies within the web-server and not on opensrp-web. If there is some way we can tweak the opensrp web payload to work with the existing constraints then let me know, otherwise this is something that can only be fixed on the web-server. 

Also tested this on opensrp web stage with the `web-v2.3.5` tag, and it did not run into the mentioned error.

cc @Naima-Bashir

**Comment by SebaMutuku** [comment] 2023-08-09 08:30
@p-netm do you mind sharing the payload on both versions.

**Comment by peterMuriuki** [comment] 2023-08-09 09:25
@SebaMutuku The following are the payloads on opensrp web stage, the organization is assigned twice to the same location and plan within a  matter of minutes. I do not have credentials to the `web.ancs.dev.sid` instance, so I do not have those. 

```

{
  "0": {
    "fromDate": "2023-08-07T16:05:05+03:00",
    "jurisdiction": "05d0fb90-5a0d-4f6d-92b2-110224818fdf",
    "organization": "c53900dd-cb8e-4f9f-befc-5b21742612a1",
    "plan": "8a602d51-707a-444c-aad2-305ba869e4ad",
    "toDate": "2033-08-07T16:05:05+03:00"
  }
}

{
  "0": {
    "fromDate": "2023-08-07T03:00:00+03:00", - looks like api casts down the assignments to start of day.
    "jurisdiction": "05d0fb90-5a0d-4f6d-92b2-110224818fdf",
    "organization": "c53900dd-cb8e-4f9f-befc-5b21742612a1",
    "plan": "8a602d51-707a-444c-aad2-305ba869e4ad",
    "toDate": "2023-08-07T16:05:40+03:00"
  }


{
  "0": {
    "fromDate": "2023-08-07T16:06:55+03:00",
    "jurisdiction": "05d0fb90-5a0d-4f6d-92b2-110224818fdf",
    "organization": "c53900dd-cb8e-4f9f-befc-5b21742612a1",
    "plan": "8a602d51-707a-444c-aad2-305ba869e4ad",
    "toDate": "2033-08-07T16:06:55+03:00"
  }
}

{
  "0": {
    "fromDate": "2023-08-07T03:00:00+03:00",
    "jurisdiction": "05d0fb90-5a0d-4f6d-92b2-110224818fdf",
    "organization": "c53900dd-cb8e-4f9f-befc-5b21742612a1",
    "plan": "8a602d51-707a-444c-aad2-305ba869e4ad",
    "toDate": "2023-08-07T16:08:26+03:00"
  }
}
```

**Comment by Naima-Bashir** [comment] 2023-08-09 12:02
Hi @p-netm I have shared the credentials via Bitwarden. Check slack for the link

**Comment by hilpitome** [comment] 2023-08-09 16:23
From the trouble shooting we did with @ndegwamartin and @Rkareko we found that the time being returned by the `from_date` field when fetching the organization-location-plan assignments is a day behind.  if you convert the timestamp provided by the endpoint `rest/organization/assignedLocationsAndPlans?plan=e61d5e83-4600-5dce-8996-68ffe6a3e2a1`, it will be `2023-07-20.`
```JSON
   {
        "organizationId": "7b4b1b3d-507d-4bdb-9109-d551a8a69d8f",
        "jurisdictionId": "8107c2aa-ade3-4a73-bbb7-6efb7f274368",
        "planId": "e61d5e83-4600-5dce-8996-68ffe6a3e2a1",
        "fromDate":` 1689872400000,`
        "toDate": 2005491600000
    }
```
If you check the following  record `(id 336)` in the team.organization_location table where the record resides, you will see that the `from_date` is` 2023-07-21`
```
 select * from team.organization_location where organization_id = 177;
 id  | organization_id | location_id | plan_id | from_date  |  to_date   |        duration         
-----+-----------------+-------------+---------+------------+------------+-------------------------
 339 |             177 |         207 |       2 | 2023-07-28 | 2023-08-03 | [2023-07-27,2023-08-04)
 259 |             177 |         199 |       2 | 2023-07-18 | 2023-07-20 | [2023-07-17,2023-07-21)
 336 |             177 |         199 |       2 | 2023-07-21 | 2033-07-21 | [2023-07-21,2033-07-22)
 253 |             177 |         201 |       2 | 2023-07-18 | 2023-07-28 | [2023-07-17,2023-07-29)
 344 |             177 |         201 |       2 | 2023-07-31 | 2033-07-31 | [2023-07-30,2033-08-01)
(5 rows)
```
This from date (2023-08-20) is what will be used in the post endpoint to [unassign/expire](https://github.com/opensrp/opensrp-server-core/blob/268cd4507bdcb301664c97683b20f6505583cb2b/src/main/java/org/opensrp/repository/postgres/OrganizationRepositoryImpl.java) the team to that location. It will try doing so by making the plan date as today. However, parts of that period is already included  in the duration of record with id `336` above hence the 400 error.
cc @Naima-Bashir @p-netm

**Comment by Naima-Bashir** [comment] 2023-08-10 07:31
NOTES FROM THE MEETING: 
1. Confirm if the From date and To date match the record in the DB
`{
    "fromDate": "2023-07-20T20:00:00+03:00",
    "jurisdiction": "8107c2aa-ade3-4a73-bbb7-6efb7f274368",
    "organization": "7b4b1b3d-507d-4bdb-9109-d551a8a69d8f",
    "plan": "e61d5e83-4600-5dce-8996-68ffe6a3e2a1",
    "toDate": "2023-08-09T17:53:54+03:00"
  }`
this corresponds to the payload above:
`336 |             177 |         199 |       2 | 2023-07-21 | 2033-07-21 | [2023-07-21,2033-07-22)`

2. Question: Could the timezone difference be the issue here?
3. The OpenSRP web receives the correct dates and sends back the correct date. e.g it receives 20th and sends back 20th to the OpenSRP server. The OpenSRP server sends 20th to the DB. 
4.  **Test: Start from the server web, do a new assignment then retrieve the record to see what time stamp we get and how the conversion is happening. The issue could be how it's stored or how it's converted when it's being retrieved.**
5. The timezone on the server is Jakarta (GMT +7) 
6. Check our own reference app servers to see if the From and To date match the duration values.
7. Confirm the timezone configuration for the DB itself.

**Comment by Naima-Bashir** [comment] 2023-08-10 10:08
We've confirmed that the timestamp is 1 day behind by assigning a new user to the location cc @Rkareko @ndegwamartin

**Comment by hilpitome** [comment] 2023-08-10 10:16
This is the record for the above assignment in the db
```
 id  | organization_id | location_id | plan_id | from_date  |  to_date   |        duration         
-----+-----------------+-------------+---------+------------+------------+-------------------------
 377 |             168 |         200 |       2 | 2023-08-10 | 2033-08-10 | [2023-08-10,2033-08-11)
```
The timestamps when fetching organization locations for the web is a day behind i.e from_date: 2023-08-09 and to_date:2023_08-09. You can see this from the json below that is returned from in the payload

```JSON
{
"organizationId": "4a52ef87-76c0-46c3-a4b8-a406260ee009",
    "jurisdictionId": "f711122e-6194-4a5a-b008-fca841f7763c",
    "planId": "e61d5e83-4600-5dce-8996-68ffe6a3e2a1",
    "fromDate": 1691600400000,
    "toDate": 2007219600000
}
```

**Comment by hilpitome** [comment] 2023-08-10 10:19
The postgres timezone is Asia/Shanghai while the server timezone is Asia/Jakarta

**Comment by hilpitome** [comment] 2023-08-11 06:13
I have tried changing the timezone to Asia/Jakarta but unfortunately it has not helped in solving the issue

**Comment by hilpitome** [comment] 2023-08-14 08:32
After ensuring that the server and postgres timezone were in sync we did some tests with @ndegwamartin  and @Naima-Bashir 
 . Location assignments seem to work for the new data created after the change though old data doesn’t, probably because it is corrupt due to the TZ difference between the DB and application server.

**Closed as completed** 2023-09-12 12:31 UTC
Labels: SID, Tech Partner (SID Team), Sl@b bug, top priority, critical, 2023 enhancements
