### ISSUE TITLE
Client's data cannot be synced based on team hierarchy

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#704] opened 2021-11-11 10:49 UTC
### How do we replicate the bug?

This bug has been discussed and demonstrated through zoom call with @dubdabasoduba and @Naima-Bashir 

Steps to replicate:
1. Log in using a team member username (village maternity post)
2. Register a new client and fill in one of the pages (quick check, test, etc)
3. Save and sync the new data
4. Log out of that username
5. Log in using a team supervisor username (community health center)
6. Data that was filled in by the team member previously could not be found

### How is this feature expected to work?

Health workers that work in the health center (team supervisor) above the maternity post (team member) should be able to access (view, edit, save any new changes) the client's data that was registered and filled in by health workers (midwives) in the maternity post.

**Comment by Naima-Bashir** [comment] 2021-11-25 14:16
Currently the ANC app operates on team visibility. Changing multiple teams to one supervisor is the request.

**Comment by dubdabasoduba** [comment] 2021-11-30 15:07
@Naima-Bashir This is not implemented on WHO ANC but it's implemented on the CHW apps. We can scope the work and figure out how to implement it.

**Comment by ellyasafaa** [comment] 2021-12-01 06:23
@dubdabasoduba Interesting, how can we proceed with that? does it work well on the CHW apps? could you demo us what has been implemented on the CHW apps?

**Comment by dubdabasoduba** [comment] 2021-12-06 14:22
@ellyasafaa Waiting for feedback here https://opensrp.slack.com/archives/C02FPRBPWCU/p1638362818009300

**Comment by Naima-Bashir** [comment] 2021-12-07 09:05
So, the mother will come to two points of care that have a different level of hierarchy: Sub-district (upper level of the village), in this case, is Public Health Center (Puskesmas), and Village, in this case, is Village Health Post (Posyandu) or Village Health Clinic (Polindes), so the issue is the provider in the sub-district level needs to be able to access the data from the village level, but not the other way around because, in the sub-district level, the coverage of the pregnant mother is including all of the villages in the sub-district.
For the deployment, there must be a data-sharing ability between these two-level. So:
1. The PHC midwife and the doctor (sub-district level) is able to create a new mother record assigned to the specific village, and the village-level user, in this case, is the village midwife should be able to access and edit the data that has been entered by the PHC midwife.
2. The village midwife is able to create a new mother record and the PHC midwife (sub-district level) can access and edit the data that has been created by the village midwife if the mother visits the PHC due to referral for doing a lab test, or specific high-risk pregnancy treatment.
3. Because some FHWs have specific authorities, like Nutritionists for example, and CHW, only able to fill in some specific information in the form, it is better to create limited access for these different FHWs.
![image](https://user-images.githubusercontent.com/61143692/144999262-91e1d2e9-3749-4775-b56e-c647312832ef.png)

**Comment by Naima-Bashir** [comment] 2022-01-10 08:17
this is more of a server configuration. @dubdabasoduba @junaidwarsivd any updates on this?

**Comment by Naima-Bashir** [comment] 2022-01-12 11:44
@elwinameylentia was this fixed? Kindly confirm so that we can close it, thanks

**Comment by Naima-Bashir** [comment] 2022-01-13 08:28
Update: @elwinameylentia and team should Please change the TEAM_ID here to LOCATION then test he hierarchy sync issue.
They are to test it today and provide feedback tomorrow. 
Then we can figure out the next steps.

**Comment by Naima-Bashir** [comment] 2022-01-25 07:39
The SID team have already implemented the suggestions from Ona and are currently testing the result.

**Comment by Naima-Bashir** [comment] 2022-02-09 07:20
Hi @ellyasafaa @elwinameylentia can we close this ticket?

**Comment by Naima-Bashir** [comment] 2022-03-02 11:25
Closing this

**Closed by Naima-Bashir** 2022-03-02 11:25 UTC
Labels: enhancement, general app updates(WHO ANC), investigation, client testing
