### ISSUE TITLE
Register Page: Trying to take a photo of a woman button causes an app crash when clicked many times

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-anc#651] opened 2021-09-21 10:03 UTC
### How do we replicate the bug?

1. Login to the app
2. Go to the Register Page 
3. Select the Take a Picture of a woman button 
4. Click the button afew times 
5. Observe if the app crashes 
6. NOTE: If installing the app for the first time, try and refuse the permissions to camera and observe if it will still take a picture. 

### How is this feature expected to work?

Expectations: 
1. The button should work as expected and take a photo of a woman. 
2. Not that it works if one clicks on the button after giving permissions to the camera 

Link to excel sheet can be found [here](https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130)

### Please Share other relevant information about the bug

Link to excel sheet can be found [here](https://docs.google.com/spreadsheets/d/1U8e3NYO_AStHxdXZUd2tEP-AHguNGUZU/edit#gid=1219538130)
![Screenshot_20210920-141821_WHO ANC](https://user-images.githubusercontent.com/61143692/134152021-ec06609e-d536-44ba-ab51-93e534ef5d4c.jpg)

**Comment by hamza-vd** [comment] 2021-09-28 07:43
@Naima-Bashir 

I am unable to reproduce this issue at my end. I faced no crash while taking picture from `TAKE A PICTURE OF THE WOMAN` button. The functionality is working as intended. Can you please provide more details about the device and Android version on which this bug is appearing?

**Devices used for testing:**
1. Samsung Galaxy A32 with Android 11
2. Samsung Galaxy Note 9 with Android 10
3. Emulator with Android 11
4. Emulator with Android 7.0

**Scenarios tested**
- Open the register app > Deny all permissions
     - Camera did not open and the app didn't crash
     - App didn't crash even after tapping the button a few times. 
- Open the register app > Allow all permissions
     - Camera was launched and the image was taken successfully.
     - App didn't crash even after tapping the button a few times.

**Comment by ellyasafaa** [comment] 2021-09-30 04:11
Hi @hamza-vd, could you try on Samsung A21s Android 10 or Android 11?

**Comment by hamza-vd** [comment] 2021-09-30 06:52
@ellyasafaa 
Unfortunately, I don't have an A21s available for testing right now. But I have managed to test it on Android 10 and 11 devices (mentioned above), both were from Samsung and I didn't face any crashes on these. Maybe this issue is fixed in the latest native-forms library version that we are using now in ANC.  We can have the QA again, and if it still persists we have to arrange the specific device and test.

**Comment by ellyasafaa** [comment] 2021-10-01 05:51
@hamza-vd I didn't test the wrong version, did I? The apps is this the one that Ben shared  here https://opensrp.slack.com/archives/C92GVBDU7/p1629309868039700?thread_ts=1629287457.039100&cid=C92GVBDU7

**Closed** 2021-10-01 13:34 UTC
Labels: Bug Report, Can't Replicate
