### ISSUE TITLE
[Ona Support Request]: Changing the app from using the TeamID to Location ID for sync

### ISSUE THREAD

**Issue by mergygayatri** [opensrp/opensrp-client-anc#927] opened 2023-02-02 09:29 UTC
### Affected App or Server Version

1.6.17

### What kind of support do you need?

We need to switch from TeamID to LocationID.
We would like to facilitate midwives in 6 Community Health Centers (Puskesmas) to use BUNDA App. For your information, the Community health center is at the sub-district level. So, each Community Health Center consists of some villages, and the number of villages varies in each Community Health Center. Every Community Health Center has 1 coordinator midwife and some midwives to provide ANC. I

Each village usually has one Village Health Post (Poskesdes), which the ANC is provided by a village midwife. 

Pregnant women may come to both Community Health Center and Village Health post. 

I am requesting to switch TeamID to LocationID, so both midwives in Community Health Centres and Village Health Post can access the same pregnant women to avoid a double entry. Moreover, both midwives in Community Health Center and Village Health Post can enter data into the same pregnant woman's profile in the BUNDA App.

To help you understand more about my request, you can find the visual here using this link: https://drive.google.com/file/d/1rlZXBFfBBIHIOvp5g3XAhsG63AkZ5Yd1/view?usp=sharing

### What is the acceptance criteria for your support request?

TeamID is switched to LocationID

**Comment by Naima-Bashir** [comment] 2023-02-02 14:20
Hi @mergygayatri @mentarisuharto and @aria, Ona worked on this ticket over [here](https://github.com/opensrp/opensrp-client-anc/issues/909) back in October 30th. Did your team manage to merge the changes to your PR? 
The ticket we had worked on was very similar to this one if I'm not wrong. Kindly clarify if it's different from the previous one. Thank you. 
cc @dubdabasoduba

**Comment by dubdabasoduba** [comment] 2023-02-08 12:23
Here is my understanding of the problem and the steps to fix them. 

1. You would like the CHW (community health worker) and the FHW(Facility Health worker) to view the same data because clients can be given care by either. 
2. You still what the data collected in the Facilities tagged with the correct villages/communities. 

**Solutions 1**
1. Change the application from syncing using the Team ID to syncing using the Location ID. This is done on the `gradle` file.
2. Update the ANC `ME` page to show a location hierarchy if the user is assigned to a higher location in the hierarchy. 
    - The user will now be able to select a different child location when collecting data. 
    - Update the app to use the selected location (if any)  when tagging events and clients.  If none is selected the higher location they are assigned to should be used. 
3. Train the health workers on how to switch locations when they are proving care.  

**What this solution achieves**
1. All the users will be able to see the relevant data. CHWs will only see the data from the villages but the FHW will see the data on their assigned location and any other child locations. 

What this solution does not do
1. People assigned to lower/child locations cannot view data from their parent locations.

**Comment by Naima-Bashir** [comment] 2023-02-09 07:39
Hi @mergygayatri , kindly let me pick this up and follow up. I'll get back to you

**Comment by ariadng** [comment] 2023-02-09 07:47
@dubdabasoduba thank you for the update.

Regarding the proposed solution (on the step 2), which file should we change to make the app use selected location id when submitting new client?

**Comment by SebaMutuku** [comment] 2023-02-09 08:08
@mergygayatri a CHW assigned to location A should not be able to see data in location B and vise versa. However, if one CHW is assigned to a higher location then he/she will be able to see data in descendants of the higher location i.e A and B are descendants of C(Where CHW has been assigned to location C). Have you confirmed no CHW has been assigned to a higher location or both?

**Comment by SebaMutuku** [comment] 2023-02-09 08:35
@ariadng this is on the app. To do this?
1. Login to the app
2. Select Me section 
3. Click location and choose from the lists there if several.

**Comment by ariadng** [comment] 2023-02-09 08:48
@dubdabasoduba I mean, when a user changed its location via the Me page, does the app automatically assign the new location id when it creates new client data or is there any code we need to change first?

**Comment by SebaMutuku** [comment] 2023-02-09 10:10
@ariadng as discussed we will be waiting for feedback from your end.

**Comment by Naima-Bashir** [comment] 2023-02-16 13:42
Hi @ariadng @mergygayatri , any updates on this ticket? Could you share an update here on what is working and what is not. Thank you

**Comment by Naima-Bashir** [comment] 2023-02-23 09:38
The SID is trying to implement the solution. They will create a release tomorrow and update Ona. 
These were the previous action items:

- [ ] SID to use the [OptiBP Main Branch](https://github.com/opensrp/opensrp-client-anc/tree/optibp_main) as it was updated from the main branch. They should then make their separate branch a working branch derived from either Main or Optibp. This is to ensure they can have their changes saved in case of merge conflicts.
- [ ] SID will then rebuild the app on the old repo. They will then do a change on the gradle file and change the TeamID to LocationID. They can then share a recording of how the app behaves for Ona to see.
- [ ] Ona and SID can  then discuss updates on the Thursday standup to see if there has been any progress. Slack communication is highly encouraged ahead of the call to sketch out all the midwives who should see the data and those who should not see all the data.
- [ ] Ona to share the latest web version (docker image) so that SID can update theirs.
- [ ] Ona to share a write up of the long term implementation of updating the sync functionality and the server so that it can sync the location upwards

**Comment by SebaMutuku** [comment] 2023-03-02 09:36
Issue fixed by SID dev team but @mergygayatri needs to test the same.

**Comment by Naima-Bashir** [comment] 2023-03-31 06:31
Hi @mergygayatri can we close this issue

**Comment by mergygayatri** [comment] 2023-03-31 07:11
Hi @Naima-Bashir would it be okay if we close this issue once we test in the field? We haven't done it yet because we wait for the encounter date issue and others to be solved.

**Closed** 2023-07-11 08:03 UTC
Labels: Tech Partner (SID Team)
