### ISSUE TITLE
[Ona Support Request]: Location settings crashed

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#807] opened 2022-03-25 06:02 UTC
### Affected App or Server Version

Indonesian Local client app

### What kind of support do you need?

Steps to replicate:
1. Login to the Indonesian local app
2. Click on the settings section
3. Select the location (lokasi)
4. The app will crash

https://user-images.githubusercontent.com/93704986/160063434-eff33b7d-562e-40ef-b7f4-2a7da4c25e3a.mp4

### What is the acceptance criteria for your support request?

The app doesn't crash after clicking on location

**Comment by PramaAditya** [comment] 2022-03-26 06:35
Turns out the crash will only happen if the user logged in has the Location values of **null**

**Comment by Naima-Bashir** [comment] 2022-03-28 08:16
Check if the user is assigned to a team and the team is assigned to a location. 
If the user isn't assigned to a team, that could be the cause. 
@PramaAditya @SebaMutuku

**Comment by Naima-Bashir** [comment] 2022-04-04 08:13
Hi @elwinameylentia for this particular ticket, there is no work around it. One has to make sure that a user is assigned to a team. 
@PramaAditya

**Comment by Naima-Bashir** [comment] 2022-04-08 09:06
@PramaAditya @elwinameylentia is this fixed?

**Comment by elwinameylentia** [comment] 2022-04-08 10:09
yes we can assign the location via postman now. so this is okay to close. thank you

**Closed** 2022-04-08 10:24 UTC
Labels: Tech Partner (SID Team)
