### ISSUE TITLE
OpenSRP Server-web and OpenSRP-Web not communicating with keycloak

### ISSUE THREAD

**Issue by chobela** [opensrp/opensrp-client-anc#867] opened 2022-07-25 11:24 UTC
### Affected App or Server Version

Server server web version : opensrp-server-web:v2.8.31-SNAPSHOT  | opensrp web version : web:v1.1.16

### What kind of support do you need?

We have migrated our server. We have setup everything : Kecloak, opensrp web and opensrp server. We have even dumped the old database to the new postgres container. But we are unable to login to opensrp web. After attempting to  log in, it times out.

Even when we use postman, we are unable to do so. I think keycloak and opensrp server web are not communicating. 

What we have confirmed correctly :
- urls, client secret, and variables in the config files are correct 
- Port mappings are correct in nginx, we have also restarted nginx

[docker-compose.txt](https://github.com/opensrp/opensrp-client-anc/files/9180649/docker-compose.txt)

### What is the acceptance criteria for your support request?

All Containers should be running successfully. You Should be able to login to keycloak and create users.

### Relevant Information

The exact same docker-compose file works perfectly on our other server. We have not removed or added anything to it.

**Comment by SebaMutuku** [comment] 2022-07-26 08:52
@chobela can you access the keycloak url alone?

**Comment by chobela** [comment] 2022-07-26 08:58
> @chobela can you access the keycloak url alone?

@SebaMutuku Yes I can.

**Comment by chobela** [comment] 2022-07-27 06:58
Hi @SebaMutuku I am not sure exactly what you mean concerning the Keycloak url. Is it possible if we can setup a pairing session so that we look at the issue in real time, to prevent the back and forth? Seeing that we urgently need this issue rectified.

**Comment by SebaMutuku** [comment] 2022-07-27 07:25
@chobela please schedule a pairing session from 4 p.m Kenyan time

**Comment by SebaMutuku** [comment] 2022-07-27 07:54
@chobela I cannot access the following services to know where the issue is
```
1. Keycloak ->https://keycloak.ecap.bluecodeltd.com/
2. Web (It should be running even if keycloak isn't reachable)->https://web.ecap.bluecodeltd.com/
```
Please try docker-compose restart to restart the services before our call.

**Comment by chobela** [comment] 2022-07-27 08:04
Noted. I have started all containers.

**Comment by SebaMutuku** [comment] 2022-07-27 13:52
@AngelaKabari 
we tried solving the issue and found below errors on logs.
1. `opensrp-web` instance isn't showing any real-time logs on the container
2. `opensrp-server-web ` instance shows below errors:
```
[REPORT] 27072022 13:23:51,207 WARN  [pool-8-thread-3] [KeycloakDeployment] Failed to load URLs from https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/.well-known/openid-configuration
opensrp-server-web_1  | java.net.ConnectException: Connection timed out (Connection timed out)
opensrp-server-web_1  | 	at [java.net](http://java.net/).PlainSocketImpl.socketConnect(Native Method) ~[?:?]
opensrp-server-web_1  | 	at [java.net](http://java.net/).AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
opensrp-server-web_1  | 	at [java.net](http://java.net/).AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
opensrp-server-web_1  | 	at [java.net](http://java.net/).AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
opensrp-server-web_1  | 	at [java.net](http://java.net/).SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
opensrp-server-web_1  | 	at [java.net](http://java.net/).Socket.connect(Socket.java:609) ~[?:?]
opensrp-server-web_1  | 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
opensrp-server-web_1  | 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:542) ~[httpclient-4.5.2.jar:4.5.2]
opensrp-server-web_1  | 	at org.keycloak.adapters.SniSSLSocketFactory.connectSocket(SniSSLSocketFactory.java:114) ~[keycloak-adapter-core-9.0.3.jar:9.0.3]
```
However, we are able to access https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/.well-known/openid-configuration on broswer and returns a response: Which is 
`{"issuer":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage","authorization_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/auth","token_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/token","introspection_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/userinfo","end_session_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/logout","jwks_uri":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/certs","check_session_iframe":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"id_token_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"introspection_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"introspection_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":true,"scopes_supported":["openid","web-origins","write","offline_access","profile","address","roles","email","read","phone","microprofile-jwt"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"require_request_uri_registration":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"revocation_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/revoke","revocation_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"revocation_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"device_authorization_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/auth/device","backchannel_token_delivery_modes_supported":["poll"],"backchannel_authentication_endpoint":"https://keycloak.ecap.bluecodeltd.com/auth/realms/anc-stage/protocol/openid-connect/ext/ciba/auth"}`
I would suggest Benn Simon and Muguku assist in checking both opensrp-server-web and opensrp-web.
cc @dubdabasoduba

**Comment by AngelaKabari** [comment] 2022-07-28 07:59
Escalated to the Ona SRE team: https://github.com/onaio/infrastructure/issues/6047

**Comment by AngelaKabari** [comment] 2022-08-17 12:03
@chobela a gentle reminder to share the feedback on how dividing the containers on your server setup went, so that we can consult the Ona SRE team.

**Comment by chobela** [comment] 2022-08-19 10:45
Hi @AngelaKabari , so we have split the containers. We have migrated keycloak container to another server.. But we still cannot login to opensrp web.

We perhaps need a pairing session to help us with the splitting of containers, perhaps we are splitting the incorect containers.

**Comment by chobela** [comment] 2022-08-31 13:32
I am opening another issue as advised in our last pairing session. This issue is not complete, and I am opening another related ticket

**Comment by Naima-Bashir** [comment] 2022-09-09 12:21
Closing this as the Bluecode team have confirmed it. 
![image](https://user-images.githubusercontent.com/61143692/189348693-333b7783-7b8e-42c7-9680-8376f79a5c8e.png)

**Closed by Naima-Bashir** 2022-09-09 12:21 UTC
Labels: 🚧 WIP, high priority, Tech Partner (Zambia & Rwanda)
