### ISSUE TITLE
[Bug Report]: OptiBP Widget not functional

### ISSUE THREAD

**Issue by elwinameylentia** [opensrp/opensrp-client-anc#808] opened 2022-03-30 04:24 UTC
### How do we replicate the bug?

1. Log in to the client app
2. Register new mother or continue contact
3. Go to the Physical Exam form
4. Choose OptiBP to measure blood pressure. 
5. Click Get Started, but nothing happened and the client app doesn't direct users to the OptiBP app.

This issue has also been discussed on Slack (Mar 18th

https://user-images.githubusercontent.com/93704986/160751093-7fbbdf6a-6c71-416a-9e2d-0ea236ab9ac2.mp4

)

### How is this feature expected to work?

The OptiBP widget should direct users to the OptiBP app and allow users to measure blood pressure

**Comment by Naima-Bashir** [comment] 2022-03-30 06:45
which branch are you forking from? @elwinameylentia

**Comment by Naima-Bashir** [comment] 2022-03-30 06:47
Also another possibility is that you haven't installed the optibp app. Is it possible? @elwinameylentia

**Comment by Naima-Bashir** [comment] 2022-03-30 07:07
Here is the OptiBP app from Biospectal: https://drive.google.com/u/0/uc?id=1Ms2WdY3wtE5IuXeDjok8dqKZBvCMw2Wc&export=download

**Comment by elwinameylentia** [comment] 2022-03-30 07:10
No, we have installed optibp app and log in to the optibp app too

**Comment by Naima-Bashir** [comment] 2022-03-30 07:12
Hi @elwinameylentia we are in a meeting, can you join us? prama as well. Here is the link **SID/Ona troubleshooting call
Wednesday, March 30 · 10:00 – 11:00am
Google Meet joining info
Video call link: https://meet.google.com/syx-jhxj-eca
Or dial: ‪(KE) +254 20 3893887‬ PIN: ‪443 518 834 4665‬#
More phone numbers: https://tel.meet/syx-jhxj-eca?pin=4435188344665**

**Comment by elwinameylentia** [comment] 2022-03-30 07:25
Hi Naima i'm currently in the field for the training activities. Prama has
confirmed that the team is also in the middle of troubleshooting other
issues so he couldn't join.

**Comment by Naima-Bashir** [comment] 2022-03-30 07:29
Okay no problem. We have installed your local SID app and replicated the
OptiBP issue. It is showing on both the emulator and the mobile device.

We have shared recordings of it.
Naima Bashir
Project Manager

<http://bit.ly/2aeOueY>

Mobile: +254 700 037 480


<http://bit.ly/2ckhfuf>  <http://bit.ly/2csSdWW>  <http://bit.ly/2bYdtWl>

Get a free Ona account <http://bit.ly/2buoC12>

**Comment by junaidwarsivd** [comment] 2022-03-30 07:40
@Naima-Bashir  @elwinameylentia  seems like the BP companion app is not installed in the device in order for the optibp widget to be working companion app for BP measurement should be installed on that device
Recording link is attached below https://drive.google.com/file/d/1Dlmgm6qgSxFZl8OVcIZlWsWH9-Ezw8_q/view?usp=sharing

**Comment by elwinameylentia** [comment] 2022-03-30 07:44
Have you tried to replicate it with the global app (the one created by
ONA)?

**Comment by elwinameylentia** [comment] 2022-03-30 07:51
@***@***.*** ***@***.***>
Thanks for the video. Which apk version did you use in that video?
Please use our latest version of local apk to replicate the issue
https://drive.google.com/file/d/1Zn735kSYboednI9rJNRyDgOgPehiqf-J/view
Thank you

**Comment by Naima-Bashir** [comment] 2022-03-30 08:23
Hi @elwinameylentia We used the latest one you sent us via slack [here](https://opensrp.slack.com/archives/C02FPRBPWCU/p1648031082828919?thread_ts=1647944322.476419&cid=C02FPRBPWCU)

We have also tested on our General Ona App and we can see the OptiBP widget. We look forward to our call later today so that we can troubleshoot together.

**Comment by Naima-Bashir** [comment] 2022-03-30 11:42
OptiBP widget; cloning the latest branch fixed. Issue was caused by forking the wrong branch. Ona shared the latest branch and this has fixed the optibp bug they were having.

**Comment by Naima-Bashir** [comment] 2022-03-30 12:02
Reopening this to assign to @junaidwarsivd to check the most recent optibp branch

**Comment by Naima-Bashir** [comment] 2022-04-01 07:14
This has been fixed in this release : link https://github.com/opensrp/opensrp-client-anc/releases/tag/v1.6.12 

Please clear cache beforehand

**Closed by Naima-Bashir** 2022-04-01 07:15 UTC
Labels: Bug Report, Tech Partner (SID Team)

**Comment by elwinameylentia** [comment] 2022-10-11 06:58
The team forks from optibp/merge-app-gen-update

Is this widget issue not replicated on your side?
