### ISSUE TITLE
Crash in the Profile menu while filling in Contact 2 of the care

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#662] opened 2021-10-01 06:51 UTC
### How do we replicate the bug?

Steps to check:
1. Log in to the app
2. Start the contact 2 by clicking one of the clients that has done the first contact, you will then be navigated to the Quick Check page
3. Choose the option of Scheduled contact and fill in the danger signs with none
4. Click 'Proceed to Normal Contact button' in the bottom of the page
5. Click Profile menu, you will then be navigated to Demographic Info page
6. Scroll down all the question and click Next button, there will appear date field that needs to be filled in. A bit confused in this part, why the date appeared.
7. Click Cancel or Done on the date, then the date field will appear again.
8. Click Cancel or Done on the date
9. The crash will happen

Testing Device: Samsung A21s Android 10 and 11

### How is this feature expected to work?

If we click Next button on the Demographic Info page in the Profile menu, it is supposed to navigate you to the Current Pregnancy page.

Please kindly also check it @Naima-Bashir and set it to high priority issue. I succeeded to replicate the issue with the exact same step.

### Please Share other relevant information about the bug

The video for the issue can be seen here: https://drive.google.com/file/d/1PzBqcDtBX0YKi1D0jp4j_FIwbyxGsrze/view?usp=sharing

**Comment by hamza-vd** [comment] 2021-10-01 12:25
Duplicate of #627

**Comment by Naima-Bashir** [comment] 2021-11-25 08:51
SID to confrim if it has been fixed. @elwinameylentia @ellyasafaa

**Closed** 2021-11-25 14:31 UTC
Labels: Bug Report, Sl@b bug, qa+
