### ISSUE TITLE
Investigate sync fail on the Bunda App

### ISSUE THREAD

**Issue by Naima-Bashir** [OpenSRP/opensrp-client-anc#945] opened 2023-06-22 07:27 UTC
### Affected App or Server Version

Latest apk

### What kind of support do you need?

The Bunda app sometimes takes very long to sync  (about 15 minutes for the initial sync)
We have had reports where the sync has also failed. 

Possible solutions are:

- We can investigate and see the resources (RAM,CPU etc) on the server to see how the resources are used in real time. 
- The sync failing issue could be a network issue. A possible solution is to point the app to our servers to test and see if it is still failing.
- We can also add PGBouncer to the server to help with the load (it could be that alot of people are using the server at the server). Therefore a possible solution would be to add something called PGBouncer. 

### What is the acceptance criteria for your support request?

Sync process to be faster

**Comment by hilpitome** [comment] 2023-06-29 12:56
Steps to take for this 
- [x] Update the server to its latest version
- [x] Update the client app libraries to its latest version
- [ ] Add pgbouncer

**Comment by hilpitome** [comment] 2023-07-10 09:13
I can confirm that the server is on the latest version. This is the same case for client libraries meaning that it should have any of the latest optimizations needed on the client side.

**Comment by hilpitome** [comment] 2023-07-10 09:14
I also checked the server stats during initial sync. I did not see any notable increase in the size or the CPU or RAM used.

**Comment by Naima-Bashir** [comment] 2023-07-11 08:02
Related to this https://github.com/opensrp/opensrp-client-anc/issues/959

**Comment by Naima-Bashir** [comment] 2023-07-18 08:36
This issue has been replicated: The sync is failing when the phone's device and app's device is in Bahasa. The sync is working fine when the app language is in Bahasa and phone language is in English ... the issue occurs when both phone and the app's language are in Bahasa

**Comment by Naima-Bashir** [comment] 2023-07-18 12:16
Sync fail happens when there is no new data to be synced to the server

**Comment by Naima-Bashir** [comment] 2023-07-18 13:21
From today's call: 

- Events gets saved but the clients don't get saved. Additional ID could be the reason for the sync fail. 
- We can add the missing column for the Additional ID on the server. This will take in the additional ID field

**Comment by SebaMutuku** [comment] 2023-07-18 14:29
@Naima-Bashir @AngelaKabari we've identified the fields in the identifier section are duplicated. When sync is initiated, it checks for these fields and finds a duplicate of them. It assumes a client exists on the db and proceeds to update them instead of creating a new client. Below is a sample JSON 
``` json 
 {
  "_id": "7ce79814-bdce-496c-bdca-221b94f6c920",
  "_rev": "v43",
  "type": "Client",
  "gender": "F",
  "lastName": "Dua",
  "addresses": [
    {
      "addressType": "",
      "addressFields": {
        "address2": "Summit"
      }
    }
  ],
  "birthdate": "1997-07-11T07:00:00.000+07:00",
  "firstName": "THR",
  "attributes": {
    "age": "26",
    "edd": "2024-02-07",
    "reminders": "{\"value\":\"no\",\"text\":\"\"}",
    "ssn_status": "{\"value\":\"active\",\"text\":\"\"}",
    "cohabitants": "[\"{\\\"value\\\":\\\"partner\\\",\\\"text\\\":\\\"\\\"}\"]",
    "uid_unknown": "[\"{\\\"value\\\":\\\"yes\\\",\\\"text\\\":\\\"\\\"}\"]",
    "next_contact": "8",
    "phone_number": "00000000000",
    "contact_status": "today",
    "red_flag_count": "2",
    "alt_phone_number": "0000000000",
    "next_contact_date": "2023-08-02",
    "yellow_flag_count": "1",
    "uid_unknown_reason": "{\"value\":\"dont_have\",\"text\":\"\"}",
    "phone_number_repeat": "00000000000",
    "last_contact_record_date": "2023-07-14"
  },
  "dateEdited": "2023-07-14T20:48:43.562+07:00",
  "dateCreated": "2023-07-11T18:50:29.707+07:00",
  "identifiers": {
    "ssn": "8888888888888",
    "ANC_ID": "5366950",
    "ssn_repeat": "8888888888888",
    "additional_id_type": "2222222222",
    "additional_id_number": "333333333",
    "additional_id_number_repeat": "333333333"
  },
  "baseEntityId": "21eb2f91-bf08-4e9e-bec8-f3da1d328c4e",
  "relationships": {},
  "serverVersion": 10545,
  "birthdateApprox": false,
  "deathdateApprox": false,
  "clientDatabaseVersion": 4,
  "clientApplicationVersion": 1
}
```
**We can approach this is two in ways.**

1. Ensure uniqueness of `ssn`,`ssn_repeat`,`additional_id_type`,`additional_id_number`,`additional_id_number_repeat`
2.  Move identifier fields except `ANC_ID` from `identifiers` to `attributes` . 

If we go with option 2, some of the clients data might not be visible on the app when editing the fields. We can migrate the above mentioned  from `identifiers` to `attributes` and update the json or clear all data in the backend except `settings table` for fresh start.

**Comment by junaidwarsivd** [comment] 2023-07-19 07:52
@SebaMutuku so i've used the approach to and the sync is starting to work sync was failing because the client can not be created using duplicate identifiers

**Closed as completed** 2023-08-08 08:34 UTC
Labels: enhancement, Tech Partner (SID Team), 2023 enhancements
